AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Hold That Thought - Consolidated API with Single-Table DynamoDB

Parameters:
  AllowedOrigins:
    Type: String
    Description: CORS allowed origins
    Default: '*'

  AppDomain:
    Type: String
    Description: App domain for OAuth callbacks (e.g., localhost:5173 for dev, holdthatthought.family for prod)
    Default: 'localhost:5173'

  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID (leave empty to skip Google OAuth setup)
    Default: ''

  GoogleClientSecret:
    Type: String
    Description: Google OAuth Client Secret
    Default: ''
    NoEcho: true

  TableName:
    Type: String
    Description: DynamoDB table name (single table design)
    Default: HoldThatThought

  ArchiveBucket:
    Type: String
    Description: S3 bucket for letters, media, and profile photos (single bucket architecture)

  PhotoBucket:
    Type: String
    Description: S3 bucket for profile photos
    Default: hold-test-photo

  MediaBucket:
    Type: String
    Description: S3 bucket for media attachments
    Default: hold-test-media

  SesFromEmail:
    Type: String
    Description: Email address to send notifications from (domain must be verified in SES)
    Default: noreply@holdthatthought.family

  GeminiApiKey:
    Type: String
    Description: Google Gemini API Key
    Default: ''
    NoEcho: true

Conditions:
  HasGoogleOAuth: !Not [!Equals [!Ref GoogleClientId, '']]

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 30
    MemorySize: 512
    Architectures:
      - x86_64
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      AddDefaultAuthorizerToCorsPreflight: false
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !GetAtt UserPool.Arn

Resources:
  # =============================================================================
  # Cognito User Pool
  # =============================================================================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-users'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${AWS::StackName}-client'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !Sub 'http://${AppDomain}/auth/callback'
        - !Sub 'https://${AppDomain}/auth/callback'
      LogoutURLs:
        - !Sub 'http://${AppDomain}/auth/logout'
        - !Sub 'https://${AppDomain}/auth/logout'
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      AccessTokenValidity: 4
      IdTokenValidity: 4
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days

  UserPoolClientWithGoogle:
    Type: AWS::Cognito::UserPoolClient
    Condition: HasGoogleOAuth
    DependsOn: GoogleIdentityProvider
    Properties:
      ClientName: !Sub '${AWS::StackName}-client-google'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
        - Google
      CallbackURLs:
        - !Sub 'http://${AppDomain}/auth/callback'
        - !Sub 'https://${AppDomain}/auth/callback'
      LogoutURLs:
        - !Sub 'http://${AppDomain}/auth/logout'
        - !Sub 'https://${AppDomain}/auth/logout'
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      AccessTokenValidity: 4
      IdTokenValidity: 4
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub '${AWS::StackName}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Condition: HasGoogleOAuth
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: email openid profile
      AttributeMapping:
        email: email
        name: name

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub '${AWS::StackName}-identity'
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt AuthenticatedRole.Arn

  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref IdentityPool
              ForAnyValue:StringLike:
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: CognitoAuthorizedPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessRestApi}/*'

  # =============================================================================
  # DynamoDB Single Table
  # =============================================================================
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # =============================================================================
  # Consolidated API Lambda
  # =============================================================================
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/api/
      Handler: index.handler
      Description: Consolidated API - comments, messages, profiles, reactions, media
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          ARCHIVE_BUCKET: !Ref ArchiveBucket
          LETTER_PROCESSOR_FUNCTION_NAME: !Ref LetterProcessorFunction
          SES_FROM_EMAIL: !Ref SesFromEmail
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
        - LambdaInvokePolicy:
            FunctionName: !Ref LetterProcessorFunction
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
        - S3CrudPolicy:
            BucketName: !Ref ArchiveBucket
        - S3CrudPolicy:
            BucketName: !Ref PhotoBucket
        - S3CrudPolicy:
            BucketName: !Ref MediaBucket
      Events:
        # Comments
        GetComments:
          Type: Api
          Properties:
            Path: /comments/{itemId}
            Method: get
        CreateComment:
          Type: Api
          Properties:
            Path: /comments/{itemId}
            Method: post
        EditComment:
          Type: Api
          Properties:
            Path: /comments/{itemId}/{commentId}
            Method: put
        DeleteComment:
          Type: Api
          Properties:
            Path: /comments/{itemId}/{commentId}
            Method: delete
        AdminDeleteComment:
          Type: Api
          Properties:
            Path: /admin/comments/{commentId}
            Method: delete
        # Messages
        GetConversations:
          Type: Api
          Properties:
            Path: /messages/conversations
            Method: get
        GetMessages:
          Type: Api
          Properties:
            Path: /messages/{conversationId}
            Method: get
        CreateConversation:
          Type: Api
          Properties:
            Path: /messages/conversations
            Method: post
        SendMessage:
          Type: Api
          Properties:
            Path: /messages/{conversationId}
            Method: post
        MessageUploadUrl:
          Type: Api
          Properties:
            Path: /messages/{conversationId}/upload-url
            Method: post
        AttachmentUploadUrl:
          Type: Api
          Properties:
            Path: /messages/attachments/upload-url
            Method: post
        MarkAsRead:
          Type: Api
          Properties:
            Path: /messages/{conversationId}/read
            Method: put
        DeleteConversation:
          Type: Api
          Properties:
            Path: /messages/{conversationId}
            Method: delete
        DeleteMessage:
          Type: Api
          Properties:
            Path: /messages/{conversationId}/{messageId}
            Method: delete
        # Profile
        GetProfile:
          Type: Api
          Properties:
            Path: /profile/{userId}
            Method: get
        UpdateProfile:
          Type: Api
          Properties:
            Path: /profile
            Method: put
        GetUserComments:
          Type: Api
          Properties:
            Path: /profile/{userId}/comments
            Method: get
        ProfilePhotoUploadUrl:
          Type: Api
          Properties:
            Path: /profile/photo/upload-url
            Method: post
        ListUsers:
          Type: Api
          Properties:
            Path: /users
            Method: get
        # Reactions
        GetReactions:
          Type: Api
          Properties:
            Path: /reactions/{commentId}
            Method: get
        AddReaction:
          Type: Api
          Properties:
            Path: /reactions/{commentId}
            Method: post
        RemoveReaction:
          Type: Api
          Properties:
            Path: /reactions/{commentId}
            Method: delete
        # Media
        MediaUploadUrl:
          Type: Api
          Properties:
            Path: /media/upload-url
            Method: post
        ListMedia:
          Type: Api
          Properties:
            Path: /media/list
            Method: post
        PdfDownloadUrl:
          Type: Api
          Properties:
            Path: /pdf/download-url
            Method: get
        DownloadPresignedUrl:
          Type: Api
          Properties:
            Path: /download/presigned-url
            Method: get
        # Letters
        ListLetters:
          Type: Api
          Properties:
            Path: /letters
            Method: get
        GetLetter:
          Type: Api
          Properties:
            Path: /letters/{date}
            Method: get
        UpdateLetter:
          Type: Api
          Properties:
            Path: /letters/{date}
            Method: put
        GetLetterVersions:
          Type: Api
          Properties:
            Path: /letters/{date}/versions
            Method: get
        RevertLetterVersion:
          Type: Api
          Properties:
            Path: /letters/{date}/revert
            Method: post
        GetLetterPdf:
          Type: Api
          Properties:
            Path: /letters/{date}/pdf
            Method: get
        # Letter upload/draft routes
        LetterUploadRequest:
          Type: Api
          Properties:
            Path: /letters/upload-request
            Method: post
        LetterProcess:
          Type: Api
          Properties:
            Path: /letters/process/{uploadId}
            Method: post
        ListDrafts:
          Type: Api
          Properties:
            Path: /admin/drafts
            Method: get
        GetDraft:
          Type: Api
          Properties:
            Path: /admin/drafts/{draftId}
            Method: get
        DeleteDraft:
          Type: Api
          Properties:
            Path: /admin/drafts/{draftId}
            Method: delete
        PublishDraft:
          Type: Api
          Properties:
            Path: /admin/drafts/{draftId}/publish
            Method: post
        # Contact (public - no auth required)
        SendContactMessage:
          Type: Api
          Properties:
            Path: /contact
            Method: post
            Auth:
              Authorizer: NONE

  # =============================================================================
  # Background Processors (keep separate - different triggers)
  # =============================================================================
  ActivityAggregatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/activity-aggregator/
      Handler: index.handler
      Description: Activity aggregator - update user stats from DynamoDB streams
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          USER_PROFILES_TABLE: !Ref TableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 10
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'

  NotificationProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/notification-processor/
      Handler: index.handler
      Description: Notification processor - send emails from DynamoDB streams
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          SES_FROM_EMAIL: !Ref SesFromEmail
          BASE_URL: https://holdthatthought.family
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableName
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
              Resource: '*'
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 10
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'

  LetterProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/letter-processor/
      Handler: index.handler
      Description: Letter processor - merges PDFs and parses with Gemini
      Runtime: nodejs20.x
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          ARCHIVE_BUCKET: !Ref ArchiveBucket
          GEMINI_API_KEY: !Ref GeminiApiKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
        - S3CrudPolicy:
            BucketName: !Ref ArchiveBucket

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'

  TableName:
    Description: DynamoDB Table Name
    Value: !Ref DynamoDBTable

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !If [HasGoogleOAuth, !Ref UserPoolClientWithGoogle, !Ref UserPoolClient]

  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref IdentityPool

  CognitoHostedUIUrl:
    Description: Cognito Hosted UI URL
    Value: !Sub 'https://${AWS::StackName}-${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com'

  CognitoHostedUIDomain:
    Description: Cognito Hosted UI Domain
    Value: !Sub '${AWS::StackName}-${AWS::AccountId}'

  ApiFunctionArn:
    Description: API Lambda Function ARN
    Value: !GetAtt ApiFunction.Arn
