AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda function for authenticated media uploads to S3'

Parameters:
  ProjectName:
    Type: String
    Default: 'hold-that-thought'
    Description: 'Name of the project for resource naming'
  Environment:
    Type: String
    Default: 'prod'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name'
  S3BucketName:
    Type: String
    Default: 'hold-that-thought-bucket'
    Description: 'Name of the S3 bucket for media storage'
  Region:
    Type: String
    Default: 'us-west-2'
    Description: 'AWS region for Lambda and S3'
  MaxFileSize:
    Type: Number
    Default: 5000000000
    Description: 'Maximum allowed file size in bytes (default 5gig)'
  AllowedTypes:
    Type: String
    Default: 'image/jpeg,image/png,application/pdf'
    Description: 'Comma-separated list of allowed MIME types'

Resources:
  MediaUploadLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-media-upload-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3UploadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'

  MediaUploadLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-media-upload-lambda'
      Handler: index.handler
      Role: !GetAtt MediaUploadLambdaRole.Arn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: 'lambdas/media-upload-lambda.zip' # Only application code, not tests
      Runtime: nodejs22.x
      Environment:
        Variables:
          BUCKET_NAME: !Ref S3BucketName
          REGION: !Ref Region
          MAX_FILE_SIZE: !Ref MaxFileSize
          ALLOWED_TYPES: !Ref AllowedTypes
      Timeout: 30
      MemorySize: 256

  MediaUploadLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-media-upload-lambda'
      RetentionInDays: 14

Outputs:
  MediaUploadLambdaFunctionArn:
    Description: 'ARN of the media upload Lambda function'
    Value: !GetAtt MediaUploadLambdaFunction.Arn
  MediaUploadLambdaRoleArn:
    Description: 'ARN of the Lambda execution role'
    Value: !GetAtt MediaUploadLambdaRole.Arn
