AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda function for authenticated PDF downloads from S3'

Parameters:
  ProjectName:
    Type: String
    Default: 'hold-that-thought'
    Description: 'Name of the project for resource naming'
  Environment:
    Type: String
    Default: 'prod'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name'
  S3BucketName:
    Type: String
    Default: 'hold-that-thought-bucket'
    Description: 'Name of the S3 bucket for PDF storage'
  Region:
    Type: String
    Default: 'us-west-2'
    Description: 'AWS region for Lambda and S3'

Resources:
  PdfDownloadLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-pdf-download-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3ReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'

  PdfDownloadLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-pdf-download-lambda'
      Handler: index.handler
      Role: !GetAtt PdfDownloadLambdaRole.Arn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: 'lambdas/pdf-download-lambda.zip' # Update if needed
      Runtime: nodejs22.x
      Environment:
        Variables:
          BUCKET_NAME: !Ref S3BucketName
          REGION: !Ref Region
      Timeout: 30
      MemorySize: 256

  PdfDownloadLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-pdf-download-lambda'
      RetentionInDays: 14

Outputs:
  PdfDownloadLambdaFunctionArn:
    Description: 'ARN of the PDF download Lambda function'
    Value: !GetAtt PdfDownloadLambdaFunction.Arn
  PdfDownloadLambdaRoleArn:
    Description: 'ARN of the Lambda execution role'
    Value: !GetAtt PdfDownloadLambdaRole.Arn
